### PR TITLE
Error cardano-ping whenever there's a decoding error

### PR DESCRIPTION
**Pull request by bolt12**
# Description

Fixes https://github.com/IntersectMBO/ouroboros-network/issues/4865

### CODE REVIEW

**Review by coot — CHANGES_REQUESTED** [review]
Let's define an error type which provides `displayError` in its `Exception` instance, and use it with `throwIO`.

**Comment by bolt12** [comment]
The problem is that the error messages depend on an `IO String` result

**Review by crocodile-dentist — APPROVED** [review]
LGTM

**Review by coot — APPROVED** [review]
LGTM

**Pull request merged**
