### PR TITLE
Dropped NodeToClient versions < 16

### PR DESCRIPTION
**Pull request by coot**
# Description

- **ouroboros-network-api: droped all versions < NodeToClientV_16**
- **Updated `check-changelogs.sh script**

# Checklist

### Quality
* [x] Commit sequence makes sense and have useful messages, see [ref][contrib#git-history].
* [ ] New tests are added and existing tests are updated.
* [x] Self-reviewed the PR.

### Maintenance
* [ ] Linked an [issue][link-issue] or added the PR to the current sprint of [`ouroboros-network`][project] project.
* [x] Added labels.
* [x] Updated changelog files.
* [x] The documentation has been properly updated, see [ref][contrib#documentation].

[project]: https://github.com/orgs/IntersectMBO/projects/5/views/1
[link-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=
[contrib#git-history]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#git-history
[contrib#documentation]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#documentation

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]
LGTM!

**Review by amesgen — APPROVED** [review]
Thanks, this will allow us to remove quite some cruft in Consensus :heart:

**Comment by amesgen** [comment]
Maybe doesn't have to happen in this PR, but https://github.com/IntersectMBO/ouroboros-network/blob/main/cardano-ping/src/Cardano/Network/Ping.hs still has the old versions; maybe it makes sense to keep them there for some time for e.g. debugging.

**Comment by coot** [comment]
I don't think we need to support old nodes in `cardano-ping`.

**Comment by coot** [comment]
Karl opposed removing versions from `cardano-ping`, so let's keep them.

**Pull request merged**
