### PR TITLE
Backport version bumps and changelogs from release/ouroboros-network-0.17.0.0

### PR DESCRIPTION
**Pull request by crocodile-dentist**
# Description

This backports changelogs and version bumps from release/ouroboros-network-0.17.0.0

# Checklist

### Quality
* [x] Commit sequence makes sense and have useful messages, see [ref][contrib#git-history].
* [ ] New tests are added and existing tests are updated.
* [x] Self-reviewed the PR.

### Maintenance
* [ ] Linked an [issue][link-issue] or added the PR to the current sprint of [`ouroboros-network`][project] project.
* [ ] Added labels.
* [x] Updated changelog files.
* [ ] The documentation has been properly updated, see [ref][contrib#documentation].

[project]: https://github.com/orgs/IntersectMBO/projects/5/views/1
[link-issue]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=
[contrib#git-history]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#git-history
[contrib#documentation]: https://github.com/IntersectMBO/ouroboros-network/blob/master/CONTRIBUTING.md#documentation

### CODE REVIEW

**Comment by bolt12** [comment]
I don't think there's to backport. Once we can release from master we'll do it!

**Comment by crocodile-dentist** [comment]
I've omitted 2 PR's and I've fixed one changelog where the changes that should go into 0.17 release were booked to changes that went to a release in June. Also, I've removed several of my changelog entries. I think to keep things straight we can immediately backport so we won't have to remember what was fixed or what has to be added back in.

**Review by crocodile-dentist — COMMENTED** [review]
This PR simply bumps versions to match release/ouroboros-network-0.17.0.0

**Review by bolt12 — APPROVED** [review]
LGTM

**Review by coot — COMMENTED** [review]
LGTM

**Pull request merged**
